### ISSUE TITLE
要件決め

### ISSUE THREAD

**Issue by miki5ki** [miki5ki/manabi-voice#5]
#### ユーザーはメールアドレス・パスワードでサインアップできる

- ユーザーは新規アカウント登録ページにアクセスし、メールアドレスとパスワードを入力する。
- ユーザーは登録確認のメールを受信し、メール内のリンクをクリックしてアカウントを有効化できる。
- ユーザーがすでに登録されているメールアドレスを入力した場合、エラーメッセージが表示される。
- パスワードは最低 8 文字で、大文字・小文字・数字・記号を含む強力なものを求める。

#### ユーザーはログアウトできる

- ユーザーはアプリ内のナビゲーションメニューからログアウトを選択できる。
- ログアウトするとセッションが無効化され、再度ログイン画面が表示される。

#### ユーザーはパスワードをリセットできる

- ユーザーはログイン画面から「パスワードを忘れた場合」リンクをクリックし、メールアドレスを入力する。
- ユーザーはリセットメールを受信し、メール内のリンクをクリックして新しいパスワードを設定できる。
- 新しいパスワードは、セキュリティ要件（最低 8 文字、大文字・小文字・数字・記号を含む）に従う必要がある。

#### ユーザーはチャネル作成できる

- ユーザーは「新しいチャネル作成」ボタンをクリックして、チャネル名、説明、カバー画像をアップロードできる。
- チャネル作成後、ユーザーはそのチャネルに音声コンテンツを投稿できる。
- チャネルは公開か非公開か選択でき、公開されたチャネルは他のユーザーから検索できる

#### ユーザーは音声ファイルをアップロードして、投稿の公開・非公開の選択ができる

- ユーザーは「新しい投稿」ボタンをクリックして、音声ファイルを選択し、アップロードできる。
- アップロード時、タイトル、説明、公開・非公開の設定を入力できる。
- 公開設定が「非公開」の場合、リンクを持つユーザーのみにアクセスが許可される。
- アップロード中は進行状況バーが表示され、アップロードが完了すると確認メッセージが表示される。

#### ユーザーはチャンネルや投稿にカテゴリを付与できる

- 既存に存在するカテゴリを投稿やチャンネルに付与することができる。- ユーザーはタグをクリックして、関連するコンテンツの一覧を表示できる。

#### 他のユーザーはアップロードされた音声を再生できる

- ユーザーはチャンネル内の投稿一覧から任意の投稿を選び、再生ボタンをクリックしてストリーミング再生できる。
- 音声再生中に、ユーザーは一時停止やスキップ機能を利用できる。

#### ユーザーはチャンネル内の音声にコメントを残すことができる

- ユーザーは投稿詳細ページにアクセスし、コメント入力欄に文字を入力して投稿できる。
- 投稿されたコメントはリアルタイムで表示され、他のユーザーから「いいね」などのフィードバックができる
- コメントは編集や削除ができ、削除されたコメントは他のユーザーには見えなくなる。

#### ユーザーはチャンネルや投稿を検索できる

- ユーザーはチャンネルや投稿をキーワード検索できる。
- ユーザーはチャンネルや投稿を所属するカテゴリで検索できる
- ユーザーはソートをして再生回数順、新着順、人気順などで一覧を並び替えできる。

#### ログの管理

- サービス内で発生したエラーをロギングし、分析できるようにする。
- クライアントエラー（404, 500 など）とサーバーエラーを適切に分類して保存する。

#### セッション管理

- ユーザーのセッションは安全かつ効率的に管理し、セッションのタイムアウト機能を実装する（一定期間の非活動後に自動ログアウト）。

#### キャッシュと最適化

- 頻繁にアクセスされる音声ファイルやページをキャッシュして、レスポンスを高速にする。

#### アクセスコントロール

- 管理者だけがアクセスできる管理画面を用意し、一般ユーザーが誤って重要データにアクセス・変更しないようにする。
- 管理画面のアクセスログを保持し、重要な操作の記録を残す。

#### テストの効率化
- 個人開発となるため、ユニットテスト・結合テスト・E2Eテストをそれぞれ用意し、不具合の検知をできる限り自動化して進めていく。

**Comment by ayin07030708** [comment]
ポートフォリオとして評価を得るという観点のもとレビュー

・ログインには外部ツールを使用する
=> Auth0 や Cognito などのツールを使用することで実案件のアピールにもなる

・ユーザーのロール管理
=> 今回は全てのユーザが「投稿」の権利があるが、配信者と一般ユーザで分けるロール管理ができたらポイントは高いと思う
=> UserRole 1 のユーザのみ表示・非表示などNext.jsで管理できることが評価につながる可能性大

**Comment by miki5ki** [comment]
ありがとうございます！
